@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sat Nov 25 16:49:22 +0300 2023
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim FIFO_wrapper_test_behav -key {Behavioral:sim_1:Functional:FIFO_wrapper_test} -tclbatch FIFO_wrapper_test.tcl -protoinst "protoinst_files/MyFIFO_vio.protoinst" -log simulate.log"
call xsim  FIFO_wrapper_test_behav -key {Behavioral:sim_1:Functional:FIFO_wrapper_test} -tclbatch FIFO_wrapper_test.tcl -protoinst "protoinst_files/MyFIFO_vio.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
